version: "3.5"

networks:
  mariadb:
    external: true

services:
  sync:
    build: ./build
    container_name: ${CLIENTNAME}-${SITENAME}-glpi-to-radius
    networks:
      - mariadb

  restarter:
    image: docker
    container_name: ${CLIENTNAME}-${SITENAME}-restarter
    volumes: ["/var/run/docker.sock:/var/run/docker.sock"]
    command: ["/bin/sh", "-c", "while true; do sleep ${SYNC_PERIOD}; docker start lan-sync-glpi-to-radius; done"]
    restart: unless-stopped
