version: "3.5"

networks:
  mariadb:
    external: true

x-common: &common
  logging:
    driver: "json-file"
    options:
      max-size: 32m
      max-file: "3"
  restart: unless-stopped

services:
  sync:
    <<: *common
    build: ./build
    container_name: ${CLIENTNAME}-${SITENAME}-glpi-to-radius
    networks:
      - mariadb
